### ISSUE TITLE
No module named ply

### ISSUE THREAD

**Issue by josepdecid** [jutge-org/cpp2many#1]
The following error appears when loading any sample program:

> Traceback (most recent call last):
  File "/dades/home/cpp2many/cpp2many/app/../PoliCmm/src/PoliCmm.py", line 7, in <module>
    import ply.lex as lex
ImportError: No module named ply.lex

**Comment by jordi-petit** [comment]
Thanks, the ply module was not installed. The project is quite abandonned.
